version: "3.7"
services:
  avito_api:
    image: service
    env_file:
      - .env
    build:
      context: .
      dockerfile: DockerfileTest
    ports:
      - "${APP_PORT}:${APP_PORT}"
    restart: on-failure
    depends_on:
      - postgres
    command: [ "go", "test", "./internal/db/account"]

  postgres:
    image: postgres:14.3-alpine
    env_file:
      - .env
    environment:
      log_statement: "all"
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASS}"
    #    volumes:
    #      - ./db-data/:/var/lib/postgresql/data/
    ports:
      - "${DB_PORT}:${DB_PORT}"
    command: ["postgres", "-c", "log_statement=all"]

networks:
  nt_postgres:
    driver: bridge